# Generated by Django 4.2.13 on 2024-05-28 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=32)),
                ('temprature', models.CharField(max_length=32)),
                ('description', models.TextField()),
                ('icon', models.CharField(max_length=32)),
                ('update_date', models.DateTimeField()),
                ('api_response', models.TextField()),
            ],
        ),
    ]
