# Generated by Django 4.2.13 on 2024-05-28 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weather',
            name='icon',
            field=models.CharField(max_length=255),
        ),
    ]
